Import("env")

import os


# Generates src/core/Version.h from the single source of truth
# .prompt-hub/version.md, so the firmware (and the boot splash) always
# displays the current version without any manual edit.
#
# Runs as a pre-build step. It only rewrites Version.h when the version
# actually changed, so it never triggers a needless rebuild.

project_dir = env.subst("$PROJECT_DIR")
version_md  = os.path.join(project_dir, ".prompt-hub", "version.md")
header_path = os.path.join(project_dir, "src", "core", "Version.h")


def read_version():
    try:
        with open(version_md, "r", encoding="utf-8") as f:
            return f.read().strip()
    except OSError:
        return None


def render(version):
    return (
        "#pragma once\n"
        "\n"
        "// AUTO-GENERATED by scripts/gen_version.py from .prompt-hub/version.md.\n"
        "// Do not edit by hand: bump .prompt-hub/version.md instead.\n"
        "\n"
        f'#define FIRMWARE_VERSION "{version}"\n'
    )


def main():
    version = read_version()
    if not version:
        print(">>> gen_version: .prompt-hub/version.md unreadable, keeping existing Version.h")
        return

    content = render(version)
    current = None
    if os.path.exists(header_path):
        with open(header_path, "r", encoding="utf-8") as f:
            current = f.read()

    if current == content:
        return

    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f">>> gen_version: Version.h updated to {version}")


main()
